export const items=[
    {
        image:"https://images.unsplash.com/photo-1631515243349-e0cb75fb8d3a?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1188&q=80",
        tag:"must try",
        supportingTag: "bestseller",
        name : "Barbeque pure veg in a box",
        price: "789/-",
        listing : "starters,tandoori tikka,panner butter masala,indian rotis,aloo tikka gulab jamun,sweets and salads",
        minus:"fa-solid fa-minus",
        cart:"add",
        add:"fa-solid fa-plus",

    },
    {
        image:"https://images.unsplash.com/photo-1476224203421-9ac39bcb3327?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2070&q=80",
        tag:"must try",
        supportingTag: "bestseller",
        name : "Best bagara rice and chicken curry",
        price: "389/-",
        listing : "starters,tandoori tikka,panner butter masala,indian rotis,aloo tikka gulab jamun,sweets and salads",
        minus:"fa-solid fa-minus",
        cart:"add",
        add:"fa-solid fa-plus",
    },
    {
        image:"https://images.unsplash.com/photo-1455619452474-d2be8b1e70cd?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1170&q=80",
        tag:"must try",
        supportingTag: "bestseller",
        name : "Barbeque pure nonveg in a box",
        price: "1089/-",
        listing : "starters,tandoori tikka,panner butter masala,indian rotis,aloo tikka gulab jamun,sweets and salads",
        minus:"fa-solid fa-minus",
        cart:"add",
        add:"fa-solid fa-plus",
    },
    {
        image:"https://images.unsplash.com/photo-1496116218417-1a781b1c416c?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1170&q=80",
        tag:"must try",
        supportingTag: "bestseller",
        name : "Barbeque pride veg",
        price: "789/-",
        listing : "starters,tandoori tikka,panner butter masala,indian rotis,aloo tikka gulab jamun,sweets and salads",
        minus:"fa-solid fa-minus",
        cart:"add",
        add:"fa-solid fa-plus",
    },
    {
        image:"https://images.unsplash.com/photo-1470337458703-46ad1756a187?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1169&q=80",
        tag:"must try",
        supportingTag: "bestseller",
        name : "Barbeque pride non veg",
        price: "1189/-",
        listing : "starters,tandoori tikka,panner butter masala,indian rotis,aloo tikka gulab jamun,sweets and salads",
        minus:"fa-solid fa-minus",
        cart:"add",
        add:"fa-solid fa-plus",
    },
    {
        image:"https://images.unsplash.com/photo-1475090169767-40ed8d18f67d?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1332&q=80",
        tag:"must try",
        supportingTag: "bestseller",
        name : "Sri Anjaneya Restaurant",
        price: "300/-",
        listing : "starters,tandoori tikka,panner butter masala,indian rotis,aloo tikka gulab jamun,sweets and salads",
        minus:"fa-solid fa-minus",
        cart:"add",
        add:"fa-solid fa-plus",
    },
    {
        image:"https://images.unsplash.com/photo-1563379926898-05f4575a45d8?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1170&q=80",
        tag:"must try",
        supportingTag: "bestseller",
        name : "Star Dum Biryani ",
        price: "299/-",
        listing : "starters,tandoori tikka,panner butter masala,indian rotis,aloo tikka gulab jamun,sweets and salads",
        minus:"fa-solid fa-minus",
        cart:"add",
        add:"fa-solid fa-plus",
    },
    {
        image:"https://plus.unsplash.com/premium_photo-1683121324382-d35dc2c32bdb?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1170&q=80",
        tag:"try",
        supportingTag: "bestseller",
        name : "Chacos and pizzarie PVP",
        price: "189/-",
        listing : "Pizzas,Chacostandoori tikka,panner butter masala,indian rotis,aloo tikka gulab jamun,sweets and salads",
        minus:"fa-solid fa-minus",
        cart:"add",
        add:"fa-solid fa-plus",

    },
    {
        image:"https://plus.unsplash.com/premium_photo-1684923610927-326aa9ca327a?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1170&q=80",
        tag:"must try",
        supportingTag: "best",
        name : "Nuggets and Rools hub ",
        price: "310/-",
        listing : "starters,tandoori tikka,panner  butter masala,indian rotis,aloo tikka gulab jamun,sweets and salads",
        minus:"fa-solid fa-minus",
        cart:"add",
        add:"fa-solid fa-plus",
    },
    
    {
        image:"https://images.unsplash.com/photo-1577303935007-0d306ee638cf?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1140&q=80",
        tag:"must try",
        supportingTag: "bestseller",
        name : "Tandoori Hub",
        price: "450/-",
        listing : "starters,tandoori tikka,panner butter masala,indian rotis,aloo tikka gulab jamun,sweets and salads",
        minus:"fa-solid fa-minus",
        cart:"add",
        add:"fa-solid fa-plus",
    },
    {
        image:"https://images.unsplash.com/photo-1544025162-d76694265947?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1169&q=80",
        tag:"must try",
        supportingTag: "bestseller",
        name : "Kava cafe and longue ",
        price: "399/-",
        listing : "starters,tandoori tikka,panner butter masala,indian rotis,aloo tikka gulab jamun,sweets and salads",
        minus:"fa-solid fa-minus",
        cart:"add",
        add:"fa-solid fa-plus",
    },
    {
        image:"https://images.unsplash.com/photo-1631515243349-e0cb75fb8d3a?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1188&q=80",
        tag:"must try",
        supportingTag: "bestseller",
        name : "Barbeque pure veg in a box",
        price: "789/-",
        listing : "starters,tandoori tikka,panner butter masala,indian rotis,aloo tikka gulab jamun,sweets and salads",
        minus:"fa-solid fa-minus",
        cart:"add",
        add:"fa-solid fa-plus",

    },
    {
        image:"https://images.unsplash.com/photo-1476224203421-9ac39bcb3327?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2070&q=80",
        tag:"must try",
        supportingTag: "bestseller",
        name : "Best bagara rice and chicken curry",
        price: "389/-",
        listing : "starters,tandoori tikka,panner butter masala,indian rotis,aloo tikka gulab jamun,sweets and salads",
        minus:"fa-solid fa-minus",
        cart:"add",
        add:"fa-solid fa-plus",
    },
    {
        image:"https://images.unsplash.com/photo-1455619452474-d2be8b1e70cd?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1170&q=80",
        tag:"must try",
        supportingTag: "bestseller",
        name : "Barbeque pure nonveg in a box",
        price: "1089/-",
        listing : "starters,tandoori tikka,panner butter masala,indian rotis,aloo tikka gulab jamun,sweets and salads",
        minus:"fa-solid fa-minus",
        cart:"add",
        add:"fa-solid fa-plus",
    },
    {
        image:"https://images.unsplash.com/photo-1496116218417-1a781b1c416c?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1170&q=80",
        tag:"must try",
        supportingTag: "bestseller",
        name : "Barbeque pride veg",
        price: "789/-",
        listing : "starters,tandoori tikka,panner butter masala,indian rotis,aloo tikka gulab jamun,sweets and salads",
        minus:"fa-solid fa-minus",
        cart:"add",
        add:"fa-solid fa-plus",
    },
    {
        image:"https://images.unsplash.com/photo-1470337458703-46ad1756a187?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1169&q=80",
        tag:"must try",
        supportingTag: "bestseller",
        name : "Barbeque pride non veg",
        price: "1189/-",
        listing : "starters,tandoori tikka,panner butter masala,indian rotis,aloo tikka gulab jamun,sweets and salads",
        minus:"fa-solid fa-minus",
        cart:"add",
        add:"fa-solid fa-plus",
    },
    {
        image:"https://images.unsplash.com/photo-1475090169767-40ed8d18f67d?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1332&q=80",
        tag:"must try",
        supportingTag: "bestseller",
        name : "Sri Anjaneya Restaurant",
        price: "300/-",
        listing : "starters,tandoori tikka,panner butter masala,indian rotis,aloo tikka gulab jamun,sweets and salads",
        minus:"fa-solid fa-minus",
        cart:"add",
        add:"fa-solid fa-plus",
    },
    {
        image:"https://images.unsplash.com/photo-1563379926898-05f4575a45d8?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1170&q=80",
        tag:"must try",
        supportingTag: "bestseller",
        name : "Star Dum Biryani ",
        price: "299/-",
        listing : "starters,tandoori tikka,panner butter masala,indian rotis,aloo tikka gulab jamun,sweets and salads",
        minus:"fa-solid fa-minus",
        cart:"add",
        add:"fa-solid fa-plus",
    },
    {
        image:"https://plus.unsplash.com/premium_photo-1683121324382-d35dc2c32bdb?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1170&q=80",
        tag:"try",
        supportingTag: "bestseller",
        name : "Chacos and pizzarie PVP",
        price: "189/-",
        listing : "Pizzas,Chacostandoori tikka,panner butter masala,indian rotis,aloo tikka gulab jamun,sweets and salads",
        minus:"fa-solid fa-minus",
        cart:"add",
        add:"fa-solid fa-plus",

    },
    {
        image:"https://plus.unsplash.com/premium_photo-1684923610927-326aa9ca327a?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1170&q=80",
        tag:"must try",
        supportingTag: "best",
        name : "Nuggets and Rools hub ",
        price: "310/-",
        listing : "starters,tandoori tikka,panner  butter masala,indian rotis,aloo tikka gulab jamun,sweets and salads",
        minus:"fa-solid fa-minus",
        cart:"add",
        add:"fa-solid fa-plus",
    },
    
    {
        image:"https://images.unsplash.com/photo-1577303935007-0d306ee638cf?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1140&q=80",
        tag:"must try",
        supportingTag: "bestseller",
        name : "Tandoori Hub",
        price: "450/-",
        listing : "starters,tandoori tikka,panner butter masala,indian rotis,aloo tikka gulab jamun,sweets and salads",
        minus:"fa-solid fa-minus",
        cart:"add",
        add:"fa-solid fa-plus",
    },
    {
        image:"https://images.unsplash.com/photo-1544025162-d76694265947?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1169&q=80",
        tag:"must try",
        supportingTag: "bestseller",
        name : "Kava cafe and longue ",
        price: "399/-",
        listing : "starters,tandoori tikka,panner butter masala,indian rotis,aloo tikka gulab jamun,sweets and salads",
        minus:"fa-solid fa-minus",
        cart:"add",
        add:"fa-solid fa-plus",
    },
    {
        image:"https://images.unsplash.com/photo-1631515243349-e0cb75fb8d3a?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1188&q=80",
        tag:"must try",
        supportingTag: "bestseller",
        name : "Barbeque pure veg in a box",
        price: "789/-",
        listing : "starters,tandoori tikka,panner butter masala,indian rotis,aloo tikka gulab jamun,sweets and salads",
        minus:"fa-solid fa-minus",
        cart:"add",
        add:"fa-solid fa-plus",

    },
    {
        image:"https://images.unsplash.com/photo-1476224203421-9ac39bcb3327?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2070&q=80",
        tag:"must try",
        supportingTag: "bestseller",
        name : "Best bagara rice and chicken curry",
        price: "389/-",
        listing : "starters,tandoori tikka,panner butter masala,indian rotis,aloo tikka gulab jamun,sweets and salads",
        minus:"fa-solid fa-minus",
        cart:"add",
        add:"fa-solid fa-plus",
    },
    {
        image:"https://images.unsplash.com/photo-1455619452474-d2be8b1e70cd?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1170&q=80",
        tag:"must try",
        supportingTag: "bestseller",
        name : "Barbeque pure nonveg in a box",
        price: "1089/-",
        listing : "starters,tandoori tikka,panner butter masala,indian rotis,aloo tikka gulab jamun,sweets and salads",
        minus:"fa-solid fa-minus",
        cart:"add",
        add:"fa-solid fa-plus",
    },
    {
        image:"https://images.unsplash.com/photo-1496116218417-1a781b1c416c?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1170&q=80",
        tag:"must try",
        supportingTag: "bestseller",
        name : "Barbeque pride veg",
        price: "789/-",
        listing : "starters,tandoori tikka,panner butter masala,indian rotis,aloo tikka gulab jamun,sweets and salads",
        minus:"fa-solid fa-minus",
        cart:"add",
        add:"fa-solid fa-plus",
    },
    {
        image:"https://images.unsplash.com/photo-1470337458703-46ad1756a187?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1169&q=80",
        tag:"must try",
        supportingTag: "bestseller",
        name : "Barbeque pride non veg",
        price: "1189/-",
        listing : "starters,tandoori tikka,panner butter masala,indian rotis,aloo tikka gulab jamun,sweets and salads",
        minus:"fa-solid fa-minus",
        cart:"add",
        add:"fa-solid fa-plus",
    },
    {
        image:"https://images.unsplash.com/photo-1475090169767-40ed8d18f67d?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1332&q=80",
        tag:"must try",
        supportingTag: "bestseller",
        name : "Sri Anjaneya Restaurant",
        price: "300/-",
        listing : "starters,tandoori tikka,panner butter masala,indian rotis,aloo tikka gulab jamun,sweets and salads",
        minus:"fa-solid fa-minus",
        cart:"add",
        add:"fa-solid fa-plus",
    },
    {
        image:"https://images.unsplash.com/photo-1563379926898-05f4575a45d8?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1170&q=80",
        tag:"must try",
        supportingTag: "bestseller",
        name : "Star Dum Biryani ",
        price: "299/-",
        listing : "starters,tandoori tikka,panner butter masala,indian rotis,aloo tikka gulab jamun,sweets and salads",
        minus:"fa-solid fa-minus",
        cart:"add",
        add:"fa-solid fa-plus",
    },
    {
        image:"https://plus.unsplash.com/premium_photo-1683121324382-d35dc2c32bdb?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1170&q=80",
        tag:"try",
        supportingTag: "bestseller",
        name : "Chacos and pizzarie PVP",
        price: "189/-",
        listing : "Pizzas,Chacostandoori tikka,panner butter masala,indian rotis,aloo tikka gulab jamun,sweets and salads",
        minus:"fa-solid fa-minus",
        cart:"add",
        add:"fa-solid fa-plus",

    },
    {
        image:"https://plus.unsplash.com/premium_photo-1684923610927-326aa9ca327a?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1170&q=80",
        tag:"must try",
        supportingTag: "best",
        name : "Nuggets and Rools hub ",
        price: "310/-",
        listing : "starters,tandoori tikka,panner  butter masala,indian rotis,aloo tikka gulab jamun,sweets and salads",
        minus:"fa-solid fa-minus",
        cart:"add",
        add:"fa-solid fa-plus",
    },
    
    {
        image:"https://images.unsplash.com/photo-1577303935007-0d306ee638cf?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1140&q=80",
        tag:"must try",
        supportingTag: "bestseller",
        name : "Tandoori Hub",
        price: "450/-",
        listing : "starters,tandoori tikka,panner butter masala,indian rotis,aloo tikka gulab jamun,sweets and salads",
        minus:"fa-solid fa-minus",
        cart:"add",
        add:"fa-solid fa-plus",
    },
    {
        image:"https://images.unsplash.com/photo-1544025162-d76694265947?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1169&q=80",
        tag:"must try",
        supportingTag: "bestseller",
        name : "Kava cafe and longue ",
        price: "399/-",
        listing : "starters,tandoori tikka,panner butter masala,indian rotis,aloo tikka gulab jamun,sweets and salads",
        minus:"fa-solid fa-minus",
        cart:"add",
        add:"fa-solid fa-plus",
    },
    {
        image:"https://images.unsplash.com/photo-1631515243349-e0cb75fb8d3a?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1188&q=80",
        tag:"must try",
        supportingTag: "bestseller",
        name : "Barbeque pure veg in a box",
        price: "789/-",
        listing : "starters,tandoori tikka,panner butter masala,indian rotis,aloo tikka gulab jamun,sweets and salads",
        minus:"fa-solid fa-minus",
        cart:"add",
        add:"fa-solid fa-plus",

    },
    {
        image:"https://images.unsplash.com/photo-1476224203421-9ac39bcb3327?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2070&q=80",
        tag:"must try",
        supportingTag: "bestseller",
        name : "Best bagara rice and chicken curry",
        price: "389/-",
        listing : "starters,tandoori tikka,panner butter masala,indian rotis,aloo tikka gulab jamun,sweets and salads",
        minus:"fa-solid fa-minus",
        cart:"add",
        add:"fa-solid fa-plus",
    },
    {
        image:"https://images.unsplash.com/photo-1455619452474-d2be8b1e70cd?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1170&q=80",
        tag:"must try",
        supportingTag: "bestseller",
        name : "Barbeque pure nonveg in a box",
        price: "1089/-",
        listing : "starters,tandoori tikka,panner butter masala,indian rotis,aloo tikka gulab jamun,sweets and salads",
        minus:"fa-solid fa-minus",
        cart:"add",
        add:"fa-solid fa-plus",
    },
    {
        image:"https://images.unsplash.com/photo-1496116218417-1a781b1c416c?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1170&q=80",
        tag:"must try",
        supportingTag: "bestseller",
        name : "Barbeque pride veg",
        price: "789/-",
        listing : "starters,tandoori tikka,panner butter masala,indian rotis,aloo tikka gulab jamun,sweets and salads",
        minus:"fa-solid fa-minus",
        cart:"add",
        add:"fa-solid fa-plus",
    },
    {
        image:"https://images.unsplash.com/photo-1470337458703-46ad1756a187?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1169&q=80",
        tag:"must try",
        supportingTag: "bestseller",
        name : "Barbeque pride non veg",
        price: "1189/-",
        listing : "starters,tandoori tikka,panner butter masala,indian rotis,aloo tikka gulab jamun,sweets and salads",
        minus:"fa-solid fa-minus",
        cart:"add",
        add:"fa-solid fa-plus",
    },
    {
        image:"https://images.unsplash.com/photo-1475090169767-40ed8d18f67d?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1332&q=80",
        tag:"must try",
        supportingTag: "bestseller",
        name : "Sri Anjaneya Restaurant",
        price: "300/-",
        listing : "starters,tandoori tikka,panner butter masala,indian rotis,aloo tikka gulab jamun,sweets and salads",
        minus:"fa-solid fa-minus",
        cart:"add",
        add:"fa-solid fa-plus",
    },
    {
        image:"https://images.unsplash.com/photo-1563379926898-05f4575a45d8?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1170&q=80",
        tag:"must try",
        supportingTag: "bestseller",
        name : "Star Dum Biryani ",
        price: "299/-",
        listing : "starters,tandoori tikka,panner butter masala,indian rotis,aloo tikka gulab jamun,sweets and salads",
        minus:"fa-solid fa-minus",
        cart:"add",
        add:"fa-solid fa-plus",
    },
    {
        image:"https://plus.unsplash.com/premium_photo-1683121324382-d35dc2c32bdb?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1170&q=80",
        tag:"try",
        supportingTag: "bestseller",
        name : "Chacos and pizzarie PVP",
        price: "189/-",
        listing : "Pizzas,Chacostandoori tikka,panner butter masala,indian rotis,aloo tikka gulab jamun,sweets and salads",
        minus:"fa-solid fa-minus",
        cart:"add",
        add:"fa-solid fa-plus",

    },
    {
        image:"https://plus.unsplash.com/premium_photo-1684923610927-326aa9ca327a?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1170&q=80",
        tag:"must try",
        supportingTag: "best",
        name : "Nuggets and Rools hub ",
        price: "310/-",
        listing : "starters,tandoori tikka,panner  butter masala,indian rotis,aloo tikka gulab jamun,sweets and salads",
        minus:"fa-solid fa-minus",
        cart:"add",
        add:"fa-solid fa-plus",
    },
    
    {
        image:"https://images.unsplash.com/photo-1577303935007-0d306ee638cf?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1140&q=80",
        tag:"must try",
        supportingTag: "bestseller",
        name : "Tandoori Hub",
        price: "450/-",
        listing : "starters,tandoori tikka,panner butter masala,indian rotis,aloo tikka gulab jamun,sweets and salads",
        minus:"fa-solid fa-minus",
        cart:"add",
        add:"fa-solid fa-plus",
    },
    {
        image:"https://images.unsplash.com/photo-1544025162-d76694265947?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1169&q=80",
        tag:"must try",
        supportingTag: "bestseller",
        name : "Kava cafe and longue ",
        price: "399/-",
        listing : "starters,tandoori tikka,panner butter masala,indian rotis,aloo tikka gulab jamun,sweets and salads",
        minus:"fa-solid fa-minus",
        cart:"add",
        add:"fa-solid fa-plus",
    },
    {
        image:"https://images.unsplash.com/photo-1631515243349-e0cb75fb8d3a?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1188&q=80",
        tag:"must try",
        supportingTag: "bestseller",
        name : "Barbeque pure veg in a box",
        price: "789/-",
        listing : "starters,tandoori tikka,panner butter masala,indian rotis,aloo tikka gulab jamun,sweets and salads",
        minus:"fa-solid fa-minus",
        cart:"add",
        add:"fa-solid fa-plus",

    },
    {
        image:"https://images.unsplash.com/photo-1476224203421-9ac39bcb3327?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2070&q=80",
        tag:"must try",
        supportingTag: "bestseller",
        name : "Best bagara rice and chicken curry",
        price: "389/-",
        listing : "starters,tandoori tikka,panner butter masala,indian rotis,aloo tikka gulab jamun,sweets and salads",
        minus:"fa-solid fa-minus",
        cart:"add",
        add:"fa-solid fa-plus",
    },
    {
        image:"https://images.unsplash.com/photo-1455619452474-d2be8b1e70cd?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1170&q=80",
        tag:"must try",
        supportingTag: "bestseller",
        name : "Barbeque pure nonveg in a box",
        price: "1089/-",
        listing : "starters,tandoori tikka,panner butter masala,indian rotis,aloo tikka gulab jamun,sweets and salads",
        minus:"fa-solid fa-minus",
        cart:"add",
        add:"fa-solid fa-plus",
    },
    {
        image:"https://images.unsplash.com/photo-1496116218417-1a781b1c416c?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1170&q=80",
        tag:"must try",
        supportingTag: "bestseller",
        name : "Barbeque pride veg",
        price: "789/-",
        listing : "starters,tandoori tikka,panner butter masala,indian rotis,aloo tikka gulab jamun,sweets and salads",
        minus:"fa-solid fa-minus",
        cart:"add",
        add:"fa-solid fa-plus",
    },
    {
        image:"https://images.unsplash.com/photo-1470337458703-46ad1756a187?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1169&q=80",
        tag:"must try",
        supportingTag: "bestseller",
        name : "Barbeque pride non veg",
        price: "1189/-",
        listing : "starters,tandoori tikka,panner butter masala,indian rotis,aloo tikka gulab jamun,sweets and salads",
        minus:"fa-solid fa-minus",
        cart:"add",
        add:"fa-solid fa-plus",
    },
    {
        image:"https://images.unsplash.com/photo-1475090169767-40ed8d18f67d?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1332&q=80",
        tag:"must try",
        supportingTag: "bestseller",
        name : "Sri Anjaneya Restaurant",
        price: "300/-",
        listing : "starters,tandoori tikka,panner butter masala,indian rotis,aloo tikka gulab jamun,sweets and salads",
        minus:"fa-solid fa-minus",
        cart:"add",
        add:"fa-solid fa-plus",
    },
    {
        image:"https://images.unsplash.com/photo-1563379926898-05f4575a45d8?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1170&q=80",
        tag:"must try",
        supportingTag: "bestseller",
        name : "Star Dum Biryani ",
        price: "299/-",
        listing : "starters,tandoori tikka,panner butter masala,indian rotis,aloo tikka gulab jamun,sweets and salads",
        minus:"fa-solid fa-minus",
        cart:"add",
        add:"fa-solid fa-plus",
    },
    {
        image:"https://plus.unsplash.com/premium_photo-1683121324382-d35dc2c32bdb?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1170&q=80",
        tag:"try",
        supportingTag: "bestseller",
        name : "Chacos and pizzarie PVP",
        price: "189/-",
        listing : "Pizzas,Chacostandoori tikka,panner butter masala,indian rotis,aloo tikka gulab jamun,sweets and salads",
        minus:"fa-solid fa-minus",
        cart:"add",
        add:"fa-solid fa-plus",

    },
    {
        image:"https://plus.unsplash.com/premium_photo-1684923610927-326aa9ca327a?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1170&q=80",
        tag:"must try",
        supportingTag: "best",
        name : "Nuggets and Rools hub ",
        price: "310/-",
        listing : "starters,tandoori tikka,panner  butter masala,indian rotis,aloo tikka gulab jamun,sweets and salads",
        minus:"fa-solid fa-minus",
        cart:"add",
        add:"fa-solid fa-plus",
    },
    
    {
        image:"https://images.unsplash.com/photo-1577303935007-0d306ee638cf?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1140&q=80",
        tag:"must try",
        supportingTag: "bestseller",
        name : "Tandoori Hub",
        price: "450/-",
        listing : "starters,tandoori tikka,panner butter masala,indian rotis,aloo tikka gulab jamun,sweets and salads",
        minus:"fa-solid fa-minus",
        cart:"add",
        add:"fa-solid fa-plus",
    },
    {
        image:"https://images.unsplash.com/photo-1544025162-d76694265947?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1169&q=80",
        tag:"must try",
        supportingTag: "bestseller",
        name : "Kava cafe and longue ",
        price: "399/-",
        listing : "starters,tandoori tikka,panner butter masala,indian rotis,aloo tikka gulab jamun,sweets and salads",
        minus:"fa-solid fa-minus",
        cart:"add",
        add:"fa-solid fa-plus",
    },
    {
        image:"https://images.unsplash.com/photo-1496116218417-1a781b1c416c?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1170&q=80",
        tag:"must try",
        supportingTag: "bestseller",
        name : "Barbeque pride veg",
        price: "789/-",
        listing : "starters,tandoori tikka,panner butter masala,indian rotis,aloo tikka gulab jamun,sweets and salads",
        minus:"fa-solid fa-minus",
        cart:"add",
        add:"fa-solid fa-plus",
    },
    {
        image:"https://images.unsplash.com/photo-1470337458703-46ad1756a187?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1169&q=80",
        tag:"must try",
        supportingTag: "bestseller",
        name : "Barbeque pride non veg",
        price: "1189/-",
        listing : "starters,tandoori tikka,panner butter masala,indian rotis,aloo tikka gulab jamun,sweets and salads",
        minus:"fa-solid fa-minus",
        cart:"add",
        add:"fa-solid fa-plus",
    },
    {
        image:"https://images.unsplash.com/photo-1475090169767-40ed8d18f67d?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1332&q=80",
        tag:"must try",
        supportingTag: "bestseller",
        name : "Sri Anjaneya Restaurant",
        price: "300/-",
        listing : "starters,tandoori tikka,panner butter masala,indian rotis,aloo tikka gulab jamun,sweets and salads",
        minus:"fa-solid fa-minus",
        cart:"add",
        add:"fa-solid fa-plus",
    },
    {
        image:"https://images.unsplash.com/photo-1563379926898-05f4575a45d8?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1170&q=80",
        tag:"must try",
        supportingTag: "bestseller",
        name : "Star Dum Biryani ",
        price: "299/-",
        listing : "starters,tandoori tikka,panner butter masala,indian rotis,aloo tikka gulab jamun,sweets and salads",
        minus:"fa-solid fa-minus",
        cart:"add",
        add:"fa-solid fa-plus",
    },
    {
        image:"https://plus.unsplash.com/premium_photo-1683121324382-d35dc2c32bdb?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1170&q=80",
        tag:"try",
        supportingTag: "bestseller",
        name : "Chacos and pizzarie PVP",
        price: "189/-",
        listing : "Pizzas,Chacostandoori tikka,panner butter masala,indian rotis,aloo tikka gulab jamun,sweets and salads",
        minus:"fa-solid fa-minus",
        cart:"add",
        add:"fa-solid fa-plus",

    },
    {
        image:"https://plus.unsplash.com/premium_photo-1684923610927-326aa9ca327a?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1170&q=80",
        tag:"must try",
        supportingTag: "best",
        name : "Nuggets and Rools hub ",
        price: "310/-",
        listing : "starters,tandoori tikka,panner  butter masala,indian rotis,aloo tikka gulab jamun,sweets and salads",
        minus:"fa-solid fa-minus",
        cart:"add",
        add:"fa-solid fa-plus",
    },
    
    {
        image:"https://images.unsplash.com/photo-1577303935007-0d306ee638cf?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1140&q=80",
        tag:"must try",
        supportingTag: "bestseller",
        name : "Tandoori Hub",
        price: "450/-",
        listing : "starters,tandoori tikka,panner butter masala,indian rotis,aloo tikka gulab jamun,sweets and salads",
        minus:"fa-solid fa-minus",
        cart:"add",
        add:"fa-solid fa-plus",
    },
    {
        image:"https://images.unsplash.com/photo-1544025162-d76694265947?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1169&q=80",
        tag:"must try",
        supportingTag: "bestseller",
        name : "Kava cafe and longue ",
        price: "399/-",
        listing : "starters,tandoori tikka,panner butter masala,indian rotis,aloo tikka gulab jamun,sweets and salads",
        minus:"fa-solid fa-minus",
        cart:"add",
        add:"fa-solid fa-plus",
    },
    {
        image:"https://images.unsplash.com/photo-1631515243349-e0cb75fb8d3a?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1188&q=80",
        tag:"must try",
        supportingTag: "bestseller",
        name : "Barbeque pure veg in a box",
        price: "789/-",
        listing : "starters,tandoori tikka,panner butter masala,indian rotis,aloo tikka gulab jamun,sweets and salads",
        minus:"fa-solid fa-minus",
        cart:"add",
        add:"fa-solid fa-plus",

    },
    {
        image:"https://images.unsplash.com/photo-1476224203421-9ac39bcb3327?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2070&q=80",
        tag:"must try",
        supportingTag: "bestseller",
        name : "Best bagara rice and chicken curry",
        price: "389/-",
        listing : "starters,tandoori tikka,panner butter masala,indian rotis,aloo tikka gulab jamun,sweets and salads",
        minus:"fa-solid fa-minus",
        cart:"add",
        add:"fa-solid fa-plus",
    },
    {
        image:"https://images.unsplash.com/photo-1455619452474-d2be8b1e70cd?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1170&q=80",
        tag:"must try",
        supportingTag: "bestseller",
        name : "Barbeque pure nonveg in a box",
        price: "1089/-",
        listing : "starters,tandoori tikka,panner butter masala,indian rotis,aloo tikka gulab jamun,sweets and salads",
        minus:"fa-solid fa-minus",
        cart:"add",
        add:"fa-solid fa-plus",
    },
    {
        image:"https://images.unsplash.com/photo-1496116218417-1a781b1c416c?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1170&q=80",
        tag:"must try",
        supportingTag: "bestseller",
        name : "Barbeque pride veg",
        price: "789/-",
        listing : "starters,tandoori tikka,panner butter masala,indian rotis,aloo tikka gulab jamun,sweets and salads",
        minus:"fa-solid fa-minus",
        cart:"add",
        add:"fa-solid fa-plus",
    },
    {
        image:"https://images.unsplash.com/photo-1470337458703-46ad1756a187?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1169&q=80",
        tag:"must try",
        supportingTag: "bestseller",
        name : "Barbeque pride non veg",
        price: "1189/-",
        listing : "starters,tandoori tikka,panner butter masala,indian rotis,aloo tikka gulab jamun,sweets and salads",
        minus:"fa-solid fa-minus",
        cart:"add",
        add:"fa-solid fa-plus",
    },
    {
        image:"https://images.unsplash.com/photo-1475090169767-40ed8d18f67d?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1332&q=80",
        tag:"must try",
        supportingTag: "bestseller",
        name : "Sri Anjaneya Restaurant",
        price: "300/-",
        listing : "starters,tandoori tikka,panner butter masala,indian rotis,aloo tikka gulab jamun,sweets and salads",
        minus:"fa-solid fa-minus",
        cart:"add",
        add:"fa-solid fa-plus",
    },
    {
        image:"https://images.unsplash.com/photo-1563379926898-05f4575a45d8?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1170&q=80",
        tag:"must try",
        supportingTag: "bestseller",
        name : "Star Dum Biryani ",
        price: "299/-",
        listing : "starters,tandoori tikka,panner butter masala,indian rotis,aloo tikka gulab jamun,sweets and salads",
        minus:"fa-solid fa-minus",
        cart:"add",
        add:"fa-solid fa-plus",
    },
    {
        image:"https://plus.unsplash.com/premium_photo-1683121324382-d35dc2c32bdb?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1170&q=80",
        tag:"try",
        supportingTag: "bestseller",
        name : "Chacos and pizzarie PVP",
        price: "189/-",
        listing : "Pizzas,Chacostandoori tikka,panner butter masala,indian rotis,aloo tikka gulab jamun,sweets and salads",
        minus:"fa-solid fa-minus",
        cart:"add",
        add:"fa-solid fa-plus",

    },
    {
        image:"https://plus.unsplash.com/premium_photo-1684923610927-326aa9ca327a?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1170&q=80",
        tag:"must try",
        supportingTag: "best",
        name : "Nuggets and Rools hub ",
        price: "310/-",
        listing : "starters,tandoori tikka,panner  butter masala,indian rotis,aloo tikka gulab jamun,sweets and salads",
        minus:"fa-solid fa-minus",
        cart:"add",
        add:"fa-solid fa-plus",
    },
    
    {
        image:"https://images.unsplash.com/photo-1577303935007-0d306ee638cf?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1140&q=80",
        tag:"must try",
        supportingTag: "bestseller",
        name : "Tandoori Hub",
        price: "450/-",
        listing : "starters,tandoori tikka,panner butter masala,indian rotis,aloo tikka gulab jamun,sweets and salads",
        minus:"fa-solid fa-minus",
        cart:"add",
        add:"fa-solid fa-plus",
    },
    {
        image:"https://images.unsplash.com/photo-1544025162-d76694265947?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1169&q=80",
        tag:"must try",
        supportingTag: "bestseller",
        name : "Kava cafe and longue ",
        price: "399/-",
        listing : "starters,tandoori tikka,panner butter masala,indian rotis,aloo tikka gulab jamun,sweets and salads",
        minus:"fa-solid fa-minus",
        cart:"add",
        add:"fa-solid fa-plus",
    },
    {
        image:"https://images.unsplash.com/photo-1631515243349-e0cb75fb8d3a?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1188&q=80",
        tag:"must try",
        supportingTag: "bestseller",
        name : "Barbeque pure veg in a box",
        price: "789/-",
        listing : "starters,tandoori tikka,panner butter masala,indian rotis,aloo tikka gulab jamun,sweets and salads",
        minus:"fa-solid fa-minus",
        cart:"add",
        add:"fa-solid fa-plus",

    },
    {
        image:"https://images.unsplash.com/photo-1476224203421-9ac39bcb3327?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2070&q=80",
        tag:"must try",
        supportingTag: "bestseller",
        name : "Best bagara rice and chicken curry",
        price: "389/-",
        listing : "starters,tandoori tikka,panner butter masala,indian rotis,aloo tikka gulab jamun,sweets and salads",
        minus:"fa-solid fa-minus",
        cart:"add",
        add:"fa-solid fa-plus",
    },
    {
        image:"https://images.unsplash.com/photo-1455619452474-d2be8b1e70cd?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1170&q=80",
        tag:"must try",
        supportingTag: "bestseller",
        name : "Barbeque pure nonveg in a box",
        price: "1089/-",
        listing : "starters,tandoori tikka,panner butter masala,indian rotis,aloo tikka gulab jamun,sweets and salads",
        minus:"fa-solid fa-minus",
        cart:"add",
        add:"fa-solid fa-plus",
    },
    {
        image:"https://images.unsplash.com/photo-1496116218417-1a781b1c416c?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1170&q=80",
        tag:"must try",
        supportingTag: "bestseller",
        name : "Barbeque pride veg",
        price: "789/-",
        listing : "starters,tandoori tikka,panner butter masala,indian rotis,aloo tikka gulab jamun,sweets and salads",
        minus:"fa-solid fa-minus",
        cart:"add",
        add:"fa-solid fa-plus",
    },
    {
        image:"https://images.unsplash.com/photo-1470337458703-46ad1756a187?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1169&q=80",
        tag:"must try",
        supportingTag: "bestseller",
        name : "Barbeque pride non veg",
        price: "1189/-",
        listing : "starters,tandoori tikka,panner butter masala,indian rotis,aloo tikka gulab jamun,sweets and salads",
        minus:"fa-solid fa-minus",
        cart:"add",
        add:"fa-solid fa-plus",
    },
    {
        image:"https://images.unsplash.com/photo-1475090169767-40ed8d18f67d?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1332&q=80",
        tag:"must try",
        supportingTag: "bestseller",
        name : "Sri Anjaneya Restaurant",
        price: "300/-",
        listing : "starters,tandoori tikka,panner butter masala,indian rotis,aloo tikka gulab jamun,sweets and salads",
        minus:"fa-solid fa-minus",
        cart:"add",
        add:"fa-solid fa-plus",
    },
    {
        image:"https://images.unsplash.com/photo-1563379926898-05f4575a45d8?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1170&q=80",
        tag:"must try",
        supportingTag: "bestseller",
        name : "Star Dum Biryani ",
        price: "299/-",
        listing : "starters,tandoori tikka,panner butter masala,indian rotis,aloo tikka gulab jamun,sweets and salads",
        minus:"fa-solid fa-minus",
        cart:"add",
        add:"fa-solid fa-plus",
    },
    {
        image:"https://plus.unsplash.com/premium_photo-1683121324382-d35dc2c32bdb?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1170&q=80",
        tag:"try",
        supportingTag: "bestseller",
        name : "Chacos and pizzarie PVP",
        price: "189/-",
        listing : "Pizzas,Chacostandoori tikka,panner butter masala,indian rotis,aloo tikka gulab jamun,sweets and salads",
        minus:"fa-solid fa-minus",
        cart:"add",
        add:"fa-solid fa-plus",

    },
    {
        image:"https://plus.unsplash.com/premium_photo-1684923610927-326aa9ca327a?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1170&q=80",
        tag:"must try",
        supportingTag: "best",
        name : "Nuggets and Rools hub ",
        price: "310/-",
        listing : "starters,tandoori tikka,panner  butter masala,indian rotis,aloo tikka gulab jamun,sweets and salads",
        minus:"fa-solid fa-minus",
        cart:"add",
        add:"fa-solid fa-plus",
    },
    
    {
        image:"https://images.unsplash.com/photo-1577303935007-0d306ee638cf?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1140&q=80",
        tag:"must try",
        supportingTag: "bestseller",
        name : "Tandoori Hub",
        price: "450/-",
        listing : "starters,tandoori tikka,panner butter masala,indian rotis,aloo tikka gulab jamun,sweets and salads",
        minus:"fa-solid fa-minus",
        cart:"add",
        add:"fa-solid fa-plus",
    },
    {
        image:"https://images.unsplash.com/photo-1544025162-d76694265947?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1169&q=80",
        tag:"must try",
        supportingTag: "bestseller",
        name : "Kava cafe and longue ",
        price: "399/-",
        listing : "starters,tandoori tikka,panner butter masala,indian rotis,aloo tikka gulab jamun,sweets and salads",
        minus:"fa-solid fa-minus",
        cart:"add",
        add:"fa-solid fa-plus",
    },
    {
        image:"https://images.unsplash.com/photo-1631515243349-e0cb75fb8d3a?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1188&q=80",
        tag:"must try",
        supportingTag: "bestseller",
        name : "Barbeque pure veg in a box",
        price: "789/-",
        listing : "starters,tandoori tikka,panner butter masala,indian rotis,aloo tikka gulab jamun,sweets and salads",
        minus:"fa-solid fa-minus",
        cart:"add",
        add:"fa-solid fa-plus",

    },
    {
        image:"https://images.unsplash.com/photo-1476224203421-9ac39bcb3327?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2070&q=80",
        tag:"must try",
        supportingTag: "bestseller",
        name : "Best bagara rice and chicken curry",
        price: "389/-",
        listing : "starters,tandoori tikka,panner butter masala,indian rotis,aloo tikka gulab jamun,sweets and salads",
        minus:"fa-solid fa-minus",
        cart:"add",
        add:"fa-solid fa-plus",
    },
    {
        image:"https://images.unsplash.com/photo-1455619452474-d2be8b1e70cd?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1170&q=80",
        tag:"must try",
        supportingTag: "bestseller",
        name : "Barbeque pure nonveg in a box",
        price: "1089/-",
        listing : "starters,tandoori tikka,panner butter masala,indian rotis,aloo tikka gulab jamun,sweets and salads",
        minus:"fa-solid fa-minus",
        cart:"add",
        add:"fa-solid fa-plus",
    },
    {
        image:"https://images.unsplash.com/photo-1496116218417-1a781b1c416c?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1170&q=80",
        tag:"must try",
        supportingTag: "bestseller",
        name : "Barbeque pride veg",
        price: "789/-",
        listing : "starters,tandoori tikka,panner butter masala,indian rotis,aloo tikka gulab jamun,sweets and salads",
        minus:"fa-solid fa-minus",
        cart:"add",
        add:"fa-solid fa-plus",
    },
    {
        image:"https://images.unsplash.com/photo-1470337458703-46ad1756a187?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1169&q=80",
        tag:"must try",
        supportingTag: "bestseller",
        name : "Barbeque pride non veg",
        price: "1189/-",
        listing : "starters,tandoori tikka,panner butter masala,indian rotis,aloo tikka gulab jamun,sweets and salads",
        minus:"fa-solid fa-minus",
        cart:"add",
        add:"fa-solid fa-plus",
    },
    {
        image:"https://images.unsplash.com/photo-1475090169767-40ed8d18f67d?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1332&q=80",
        tag:"must try",
        supportingTag: "bestseller",
        name : "Sri Anjaneya Restaurant",
        price: "300/-",
        listing : "starters,tandoori tikka,panner butter masala,indian rotis,aloo tikka gulab jamun,sweets and salads",
        minus:"fa-solid fa-minus",
        cart:"add",
        add:"fa-solid fa-plus",
    },
    {
        image:"https://images.unsplash.com/photo-1563379926898-05f4575a45d8?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1170&q=80",
        tag:"must try",
        supportingTag: "bestseller",
        name : "Star Dum Biryani ",
        price: "299/-",
        listing : "starters,tandoori tikka,panner butter masala,indian rotis,aloo tikka gulab jamun,sweets and salads",
        minus:"fa-solid fa-minus",
        cart:"add",
        add:"fa-solid fa-plus",
    },
    {
        image:"https://plus.unsplash.com/premium_photo-1683121324382-d35dc2c32bdb?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1170&q=80",
        tag:"try",
        supportingTag: "bestseller",
        name : "Chacos and pizzarie PVP",
        price: "189/-",
        listing : "Pizzas,Chacostandoori tikka,panner butter masala,indian rotis,aloo tikka gulab jamun,sweets and salads",
        minus:"fa-solid fa-minus",
        cart:"add",
        add:"fa-solid fa-plus",

    },
    {
        image:"https://plus.unsplash.com/premium_photo-1684923610927-326aa9ca327a?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1170&q=80",
        tag:"must try",
        supportingTag: "best",
        name : "Nuggets and Rools hub ",
        price: "310/-",
        listing : "starters,tandoori tikka,panner  butter masala,indian rotis,aloo tikka gulab jamun,sweets and salads",
        minus:"fa-solid fa-minus",
        cart:"add",
        add:"fa-solid fa-plus",
    },
    
    {
        image:"https://images.unsplash.com/photo-1577303935007-0d306ee638cf?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1140&q=80",
        tag:"must try",
        supportingTag: "bestseller",
        name : "Tandoori Hub",
        price: "450/-",
        listing : "starters,tandoori tikka,panner butter masala,indian rotis,aloo tikka gulab jamun,sweets and salads",
        minus:"fa-solid fa-minus",
        cart:"add",
        add:"fa-solid fa-plus",
    },
    {
        image:"https://images.unsplash.com/photo-1544025162-d76694265947?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1169&q=80",
        tag:"must try",
        supportingTag: "bestseller",
        name : "Kava cafe and longue ",
        price: "399/-",
        listing : "starters,tandoori tikka,panner butter masala,indian rotis,aloo tikka gulab jamun,sweets and salads",
        minus:"fa-solid fa-minus",
        cart:"add",
        add:"fa-solid fa-plus",
    },
]
